
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranadudukabak
 */
public class Admin_Muzik_Paneli extends javax.swing.JDialog {
    
//    DefaultTableModel model;
//    DefaultTableModel model1;
    DefaultTableModel modelKlasik;
    DefaultTableModel modelJazz;
    DefaultTableModel modelPop;
    Admin_Muzik_Islemleri adminIslemleri = new Admin_Muzik_Islemleri();

    /**
     * Creates new form Admin_Paneli
     */
    public Admin_Muzik_Paneli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
//        model = (DefaultTableModel) GenelSarkiTablosu.getModel();
//        Sarkilari_Goruntule();
        
//        model1 = (DefaultTableModel) PremiumKullanicilarTablosu.getModel();
//        Premium_Kullanicilari_Goruntule();
        
        modelKlasik = (DefaultTableModel) KlasikSarkiTablosu.getModel();
        Klasik_Muzikleri_Goruntule();
        
        modelJazz = (DefaultTableModel) JazzSarkiTablosu.getModel();
        Jazz_Muzikleri_Goruntule();
        
        modelPop = (DefaultTableModel) PopSarkiTablosu.getModel();
        Pop_Muzikleri_Goruntule();
        
        String kullanici_adi  = Giris_Paneli.kullanici_adi;
        AdminAdiAlani.setText(kullanici_adi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SarkiAdiAlani = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SarkiTarihiAlani = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SarkiSanatciAlani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SarkiAlbumAlani = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SarkiTurAlani = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SarkiSureAlani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SarkiDinlenmeSayisiAlani = new javax.swing.JTextField();
        SarkiEklemeButonu = new javax.swing.JButton();
        SarkiGuncellemeButonu = new javax.swing.JButton();
        SarkiSilmeButonu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        GenelSarkiTablosu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        KlasikSarkiTablosu = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        JazzSarkiTablosu = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        PopSarkiTablosu = new javax.swing.JTable();
        MesajYazisi = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AdminAdiAlani = new javax.swing.JLabel();
        GeriButonu = new javax.swing.JButton();
        KlasikMuzikArama = new javax.swing.JTextField();
        JazzMuzikArama = new javax.swing.JTextField();
        PopMuzikArama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("    Şarkı Adı:");

        jLabel2.setText("    Şarkı Tarihi:");

        jLabel3.setText("    Şarkı Sanatçısı:");

        jLabel4.setText("    Şarkı Albüm:");

        jLabel5.setText("    Şarkı Türü:");

        SarkiTurAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SarkiTurAlaniActionPerformed(evt);
            }
        });

        jLabel6.setText("    Şarkı Süre:");

        jLabel7.setText("    Şarkı Dinlenme Sayısı:");

        SarkiEklemeButonu.setText("ŞARKI EKLE");
        SarkiEklemeButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SarkiEklemeButonuActionPerformed(evt);
            }
        });

        SarkiGuncellemeButonu.setText("ŞARKI GÜNCELLE");
        SarkiGuncellemeButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SarkiGuncellemeButonuActionPerformed(evt);
            }
        });

        SarkiSilmeButonu.setText("ŞARKI SİL");
        SarkiSilmeButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SarkiSilmeButonuActionPerformed(evt);
            }
        });

        GenelSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GenelSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenelSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(GenelSarkiTablosu);
        if (GenelSarkiTablosu.getColumnModel().getColumnCount() > 0) {
            GenelSarkiTablosu.getColumnModel().getColumn(0).setResizable(false);
            GenelSarkiTablosu.getColumnModel().getColumn(1).setResizable(false);
            GenelSarkiTablosu.getColumnModel().getColumn(2).setResizable(false);
            GenelSarkiTablosu.getColumnModel().getColumn(3).setResizable(false);
            GenelSarkiTablosu.getColumnModel().getColumn(4).setResizable(false);
            GenelSarkiTablosu.getColumnModel().getColumn(5).setResizable(false);
            GenelSarkiTablosu.getColumnModel().getColumn(6).setResizable(false);
            GenelSarkiTablosu.getColumnModel().getColumn(7).setResizable(false);
        }

        KlasikSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KlasikSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlasikSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(KlasikSarkiTablosu);
        if (KlasikSarkiTablosu.getColumnModel().getColumnCount() > 0) {
            KlasikSarkiTablosu.getColumnModel().getColumn(0).setResizable(false);
            KlasikSarkiTablosu.getColumnModel().getColumn(1).setResizable(false);
            KlasikSarkiTablosu.getColumnModel().getColumn(2).setResizable(false);
            KlasikSarkiTablosu.getColumnModel().getColumn(3).setResizable(false);
            KlasikSarkiTablosu.getColumnModel().getColumn(4).setResizable(false);
            KlasikSarkiTablosu.getColumnModel().getColumn(5).setResizable(false);
            KlasikSarkiTablosu.getColumnModel().getColumn(6).setResizable(false);
            KlasikSarkiTablosu.getColumnModel().getColumn(7).setResizable(false);
        }

        JazzSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JazzSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JazzSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(JazzSarkiTablosu);
        if (JazzSarkiTablosu.getColumnModel().getColumnCount() > 0) {
            JazzSarkiTablosu.getColumnModel().getColumn(0).setResizable(false);
            JazzSarkiTablosu.getColumnModel().getColumn(1).setResizable(false);
            JazzSarkiTablosu.getColumnModel().getColumn(2).setResizable(false);
            JazzSarkiTablosu.getColumnModel().getColumn(3).setResizable(false);
            JazzSarkiTablosu.getColumnModel().getColumn(4).setResizable(false);
            JazzSarkiTablosu.getColumnModel().getColumn(5).setResizable(false);
            JazzSarkiTablosu.getColumnModel().getColumn(6).setResizable(false);
            JazzSarkiTablosu.getColumnModel().getColumn(7).setResizable(false);
        }

        PopSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PopSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(PopSarkiTablosu);
        if (PopSarkiTablosu.getColumnModel().getColumnCount() > 0) {
            PopSarkiTablosu.getColumnModel().getColumn(0).setResizable(false);
            PopSarkiTablosu.getColumnModel().getColumn(1).setResizable(false);
            PopSarkiTablosu.getColumnModel().getColumn(2).setResizable(false);
            PopSarkiTablosu.getColumnModel().getColumn(3).setResizable(false);
            PopSarkiTablosu.getColumnModel().getColumn(4).setResizable(false);
            PopSarkiTablosu.getColumnModel().getColumn(5).setResizable(false);
            PopSarkiTablosu.getColumnModel().getColumn(6).setResizable(false);
            PopSarkiTablosu.getColumnModel().getColumn(7).setResizable(false);
        }

        MesajYazisi.setForeground(new java.awt.Color(255, 0, 153));

        jLabel8.setText("                 ADMİN");

        GeriButonu.setText("<-");
        GeriButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriButonuActionPerformed(evt);
            }
        });

        KlasikMuzikArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KlasikMuzikAramaKeyReleased(evt);
            }
        });

        JazzMuzikArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JazzMuzikAramaKeyReleased(evt);
            }
        });

        PopMuzikArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PopMuzikAramaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GeriButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(SarkiTarihiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                                        .addComponent(SarkiSanatciAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(SarkiAlbumAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(SarkiTurAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(SarkiSureAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(SarkiDinlenmeSayisiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(SarkiAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(SarkiEklemeButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(SarkiGuncellemeButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(SarkiSilmeButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(558, 558, 558)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(KlasikMuzikArama, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 585, Short.MAX_VALUE)
                                        .addComponent(MesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(803, 803, 803))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(915, 915, 915)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AdminAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JazzMuzikArama, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PopMuzikArama, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(744, 744, 744))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(SarkiAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GeriButonu))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SarkiTarihiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SarkiEklemeButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SarkiGuncellemeButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SarkiSilmeButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SarkiSanatciAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AdminAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SarkiTurAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SarkiAlbumAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SarkiSureAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SarkiDinlenmeSayisiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KlasikMuzikArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(JazzMuzikArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(PopMuzikArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(419, 419, 419))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenelSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenelSarkiTablosuMouseClicked
        // TODO add your handling code here:
        
//        int selectedrow = GenelSarkiTablosu.getSelectedRow();
//        
//        SarkiAdiAlani.setText(model.getValueAt(selectedrow, 1).toString());
//        SarkiTarihiAlani.setText(model.getValueAt(selectedrow, 2).toString());
//        SarkiSanatciAlani.setText(model.getValueAt(selectedrow, 3).toString());
//        SarkiAlbumAlani.setText(model.getValueAt(selectedrow, 4).toString());
//        SarkiTurAlani.setText(model.getValueAt(selectedrow, 5).toString());
//        SarkiSureAlani.setText(model.getValueAt(selectedrow, 6).toString());
//        SarkiDinlenmeSayisiAlani.setText(model.getValueAt(selectedrow, 7).toString());
    }//GEN-LAST:event_GenelSarkiTablosuMouseClicked

    private void KlasikSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlasikSarkiTablosuMouseClicked
        // TODO add your handling code here:
        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
        
        SarkiAdiAlani.setText(modelKlasik.getValueAt(selectedrow, 1).toString());
        SarkiTarihiAlani.setText(modelKlasik.getValueAt(selectedrow, 2).toString());
        SarkiSanatciAlani.setText(modelKlasik.getValueAt(selectedrow, 3).toString());
        SarkiAlbumAlani.setText(modelKlasik.getValueAt(selectedrow, 4).toString());
        SarkiTurAlani.setText(modelKlasik.getValueAt(selectedrow, 5).toString());
        SarkiSureAlani.setText(modelKlasik.getValueAt(selectedrow, 6).toString());
        SarkiDinlenmeSayisiAlani.setText(modelKlasik.getValueAt(selectedrow, 7).toString());
    }//GEN-LAST:event_KlasikSarkiTablosuMouseClicked

    private void JazzSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JazzSarkiTablosuMouseClicked
        // TODO add your handling code here:
        int selectedrow = JazzSarkiTablosu.getSelectedRow();
        
        SarkiAdiAlani.setText(modelJazz.getValueAt(selectedrow, 1).toString());
        SarkiTarihiAlani.setText(modelJazz.getValueAt(selectedrow, 2).toString());
        SarkiSanatciAlani.setText(modelJazz.getValueAt(selectedrow, 3).toString());
        SarkiAlbumAlani.setText(modelJazz.getValueAt(selectedrow, 4).toString());
        SarkiTurAlani.setText(modelJazz.getValueAt(selectedrow, 5).toString());
        SarkiSureAlani.setText(modelJazz.getValueAt(selectedrow, 6).toString());
        SarkiDinlenmeSayisiAlani.setText(modelJazz.getValueAt(selectedrow, 7).toString());
    }//GEN-LAST:event_JazzSarkiTablosuMouseClicked

    private void PopSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopSarkiTablosuMouseClicked
        // TODO add your handling code here:
        int selectedrow = PopSarkiTablosu.getSelectedRow();
        
        SarkiAdiAlani.setText(modelPop.getValueAt(selectedrow, 1).toString());
        SarkiTarihiAlani.setText(modelPop.getValueAt(selectedrow, 2).toString());
        SarkiSanatciAlani.setText(modelPop.getValueAt(selectedrow, 3).toString());
        SarkiAlbumAlani.setText(modelPop.getValueAt(selectedrow, 4).toString());
        SarkiTurAlani.setText(modelPop.getValueAt(selectedrow, 5).toString());
        SarkiSureAlani.setText(modelPop.getValueAt(selectedrow, 6).toString());
        SarkiDinlenmeSayisiAlani.setText(modelPop.getValueAt(selectedrow, 7).toString());
    }//GEN-LAST:event_PopSarkiTablosuMouseClicked

    private void SarkiEklemeButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SarkiEklemeButonuActionPerformed
        // TODO add your handling code here:
        String sarkiAd  =  SarkiAdiAlani.getText();
        String sarkiTarih = SarkiTarihiAlani.getText();
        String sarkiSanatci = SarkiSanatciAlani.getText();
        String sarkiAlbum = SarkiAlbumAlani.getText();
        String sarkiTur = SarkiTurAlani.getText();
        String sarkiSure = SarkiSureAlani.getText();
        String sarkiDinlenmeSayisi = SarkiDinlenmeSayisiAlani.getText();
        
        adminIslemleri.MuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
        
//        Sarkilari_Goruntule(); 
        Klasik_Muzikleri_Goruntule();
        Jazz_Muzikleri_Goruntule();
        Pop_Muzikleri_Goruntule();
    }//GEN-LAST:event_SarkiEklemeButonuActionPerformed

    private void SarkiGuncellemeButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SarkiGuncellemeButonuActionPerformed
        // TODO add your handling code here:
        String sarkiAd  =  SarkiAdiAlani.getText();
        String sarkiTarih = SarkiTarihiAlani.getText();
        String sarkiSanatci = SarkiSanatciAlani.getText();
        String sarkiAlbum = SarkiAlbumAlani.getText();
        String sarkiTur = SarkiTurAlani.getText();
        String sarkiSure = SarkiSureAlani.getText();
        String sarkiDinlenmeSayisi = SarkiDinlenmeSayisiAlani.getText();
        
        int flag = 0;
        
        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
        int selectedrow2 = JazzSarkiTablosu.getSelectedRow();
        int selectedrow3 = PopSarkiTablosu.getSelectedRow();
        
        if(selectedrow != -1) {
            flag = 1;
        } else if(selectedrow2 != -1) {
            flag = 2;
        } else if(selectedrow3 != -1){
            flag = 3;
        }
        
        if(flag == 1) {
            int id = (int) modelKlasik.getValueAt(selectedrow, 0);
            adminIslemleri.KlasikMuzikGuncelle(id, sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
            Klasik_Muzikleri_Goruntule();
        } else if(flag == 2) {
            int id2 = (int) modelJazz.getValueAt(selectedrow2, 0);
            adminIslemleri.JazzMuzikGuncelle(id2, sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
            Jazz_Muzikleri_Goruntule(); 
        } else if(flag == 3) {
            int id3 = (int) modelPop.getValueAt(selectedrow3, 0);
            adminIslemleri.PopMuzikGuncelle(id3, sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
            Pop_Muzikleri_Goruntule(); 
        }
    }//GEN-LAST:event_SarkiGuncellemeButonuActionPerformed

    private void SarkiSilmeButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SarkiSilmeButonuActionPerformed
        // TODO add your handling code here:
        String sarkiAd  =  SarkiAdiAlani.getText();
        String sarkiTarih = SarkiTarihiAlani.getText();
        String sarkiSanatci = SarkiSanatciAlani.getText();
        String sarkiAlbum = SarkiAlbumAlani.getText();
        String sarkiTur = SarkiTurAlani.getText();
        String sarkiSure = SarkiSureAlani.getText();
        String sarkiDinlenmeSayisi = SarkiDinlenmeSayisiAlani.getText();
        
        int flag = 0;
        
        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
        int selectedrow2 = JazzSarkiTablosu.getSelectedRow();
        int selectedrow3 = PopSarkiTablosu.getSelectedRow();
        
        if(selectedrow != -1) {
            flag = 1;
        } else if(selectedrow2 != -1) {
            flag = 2;
        } else if(selectedrow3 != -1){
            flag = 3;
        }
        
        if(flag == 1) {
            int id = (int) modelKlasik.getValueAt(selectedrow, 0);
            adminIslemleri.KlasikMuzikSil(id);
            Klasik_Muzikleri_Goruntule();
        } else if(flag == 2) {
            int id2 = (int) modelJazz.getValueAt(selectedrow2, 0);
            adminIslemleri.JazzMuzikSil(id2);
            Jazz_Muzikleri_Goruntule(); 
        } else if(flag == 3) {
            int id3 = (int) modelPop.getValueAt(selectedrow3, 0);
            adminIslemleri.PopMuzikSil(id3);
            Pop_Muzikleri_Goruntule(); 
        }
    }//GEN-LAST:event_SarkiSilmeButonuActionPerformed

    private void SarkiTurAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SarkiTurAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SarkiTurAlaniActionPerformed

    private void GeriButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriButonuActionPerformed
        // TODO add your handling code here:
        Giris_Paneli giris = new Giris_Paneli();
        
        Admin_Paneli adminPaneli = new Admin_Paneli(giris, true);
        setVisible(false);
            
        adminPaneli.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_GeriButonuActionPerformed

    private void KlasikMuzikAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KlasikMuzikAramaKeyReleased
        // TODO add your handling code here:
        String ara = KlasikMuzikArama.getText();
        
        Klasik_Dinamik_Ara(ara);
    }//GEN-LAST:event_KlasikMuzikAramaKeyReleased

    private void JazzMuzikAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JazzMuzikAramaKeyReleased
        // TODO add your handling code here:
        String ara = JazzMuzikArama.getText();
        
        Jazz_Dinamik_Ara(ara);
    }//GEN-LAST:event_JazzMuzikAramaKeyReleased

    private void PopMuzikAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PopMuzikAramaKeyReleased
        // TODO add your handling code here:
        String ara = PopMuzikArama.getText();
        
        Pop_Dinamik_Ara(ara);
    }//GEN-LAST:event_PopMuzikAramaKeyReleased

//    public void Sarkilari_Goruntule() {
//        
//        model.setRowCount(0);
//        
//        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
//        
//        sarkilar = adminIslemleri.SarkilariGetir();
//        
//        if (sarkilar != null ) {
//            
//            for (Sarki sarki : sarkilar) {
//                Object[] eklenecek = {sarki.getSarkiID(), sarki.getSarkiAd(), sarki.getSarkiTarih(), 
//                                      sarki.getSarkiSanatci(), sarki.getSarkiAlbum(), sarki.getSarkiTur(), 
//                                      sarki.getSarkiSure(), sarki.getDinlenmeSayisi()};
//                
//                model.addRow(eklenecek);
//            }
//        }
//    }
    
    public void Klasik_Muzikleri_Goruntule() {
        
        modelKlasik.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = adminIslemleri.KlasikSarkilariGetir();
        
        if (sarkilar != null ) {
            
            for (Sarki sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiID(), sarki.getSarkiAd(), sarki.getSarkiTarih(), 
                                      sarki.getSarkiSanatci(), sarki.getSarkiAlbum(), sarki.getSarkiTur(), 
                                      sarki.getSarkiSure(), sarki.getDinlenmeSayisi()};
                
                modelKlasik.addRow(eklenecek);
            }
        }
    }
    
    public void Jazz_Muzikleri_Goruntule() {
        
        modelJazz.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = adminIslemleri.JazzSarkilariGetir();
        
        if (sarkilar != null ) {
            
            for (Sarki sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiID(), sarki.getSarkiAd(), sarki.getSarkiTarih(), 
                                      sarki.getSarkiSanatci(), sarki.getSarkiAlbum(), sarki.getSarkiTur(), 
                                      sarki.getSarkiSure(), sarki.getDinlenmeSayisi()};
                
                modelJazz.addRow(eklenecek);
            }
        }
    }
    
    public void Pop_Muzikleri_Goruntule() {
        
        modelPop.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = adminIslemleri.PopSarkilariGetir();
        
        if (sarkilar != null ) {
            
            for (Sarki sarki : sarkilar) {
                Object[] eklenecek = {sarki.getSarkiID(), sarki.getSarkiAd(), sarki.getSarkiTarih(), 
                                      sarki.getSarkiSanatci(), sarki.getSarkiAlbum(), sarki.getSarkiTur(), 
                                      sarki.getSarkiSure(), sarki.getDinlenmeSayisi()};
                
                modelPop.addRow(eklenecek);
            }
        }
    }
    
    public void Klasik_Dinamik_Ara(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelKlasik);
        
        KlasikSarkiTablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    
    public void Jazz_Dinamik_Ara(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelJazz);
        
        JazzSarkiTablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    
    public void Pop_Dinamik_Ara(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelPop);
        
        PopSarkiTablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    
//    public void Premium_Kullanicilari_Goruntule() {
//        
//        model1.setRowCount(0);
//        
//        ArrayList<Premium_Kullanici> premiumKullanicilar = new ArrayList<Premium_Kullanici>();
//        
//        premiumKullanicilar = adminIslemleri.PremiumKullanicilariGetir();
//        
//        if (premiumKullanicilar != null ) {
//            
//            for (Premium_Kullanici premiumKullanici : premiumKullanicilar) {
//                Object[] eklenecek = {premiumKullanici.getKullaniciAd()};
//                
//                model1.addRow(eklenecek);
//            }
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Muzik_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Muzik_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Muzik_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Muzik_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin_Muzik_Paneli dialog = new Admin_Muzik_Paneli(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminAdiAlani;
    private javax.swing.JTable GenelSarkiTablosu;
    private javax.swing.JButton GeriButonu;
    private javax.swing.JTextField JazzMuzikArama;
    private javax.swing.JTable JazzSarkiTablosu;
    private javax.swing.JTextField KlasikMuzikArama;
    private javax.swing.JTable KlasikSarkiTablosu;
    private javax.swing.JLabel MesajYazisi;
    private javax.swing.JTextField PopMuzikArama;
    private javax.swing.JTable PopSarkiTablosu;
    private javax.swing.JTextField SarkiAdiAlani;
    private javax.swing.JTextField SarkiAlbumAlani;
    private javax.swing.JTextField SarkiDinlenmeSayisiAlani;
    private javax.swing.JButton SarkiEklemeButonu;
    private javax.swing.JButton SarkiGuncellemeButonu;
    private javax.swing.JTextField SarkiSanatciAlani;
    private javax.swing.JButton SarkiSilmeButonu;
    private javax.swing.JTextField SarkiSureAlani;
    private javax.swing.JTextField SarkiTarihiAlani;
    private javax.swing.JTextField SarkiTurAlani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
