
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranadudukabak
 */
public class Admin_Sanatci_Paneli extends javax.swing.JDialog {

    
    DefaultTableModel modelSanatci;
    Admin_Sanatci_Islemleri adminSanatciIslemleri = new Admin_Sanatci_Islemleri();
    /**
     * Creates new form Admin_Sanatci_Paneli
     */
    public Admin_Sanatci_Paneli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        modelSanatci = (DefaultTableModel) SanatciTablosu.getModel();
        Sanatcilari_Goruntule();
        
        String kullanici_adi  = Giris_Paneli.kullanici_adi;
        AdminAdiAlani.setText(kullanici_adi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SanatciAdiAlani = new javax.swing.JTextField();
        SanatciUlkesiAlani = new javax.swing.JTextField();
        SanatciArama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SanatciTablosu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        GeriButonu = new javax.swing.JButton();
        AdminAdiAlani = new javax.swing.JLabel();
        EkleButonu = new javax.swing.JButton();
        GuncelleButonu = new javax.swing.JButton();
        SilButonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("           Sanatçı Adı:");

        jLabel2.setText("           Sanatçı Ülkesi:");

        SanatciAdiAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanatciAdiAlaniActionPerformed(evt);
            }
        });

        SanatciArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanatciAramaActionPerformed(evt);
            }
        });
        SanatciArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SanatciAramaKeyReleased(evt);
            }
        });

        SanatciTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sanatçı ID", "Sanatçı Adı", "Sanatçı Ülke"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SanatciTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SanatciTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SanatciTablosu);
        if (SanatciTablosu.getColumnModel().getColumnCount() > 0) {
            SanatciTablosu.getColumnModel().getColumn(0).setResizable(false);
            SanatciTablosu.getColumnModel().getColumn(1).setResizable(false);
            SanatciTablosu.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setText("         ADMIN");

        GeriButonu.setText("<-");
        GeriButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriButonuActionPerformed(evt);
            }
        });

        EkleButonu.setText("EKLE");
        EkleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleButonuActionPerformed(evt);
            }
        });

        GuncelleButonu.setText("GÜNCELLE");
        GuncelleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuncelleButonuActionPerformed(evt);
            }
        });

        SilButonu.setText("SİL");
        SilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GeriButonu)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EkleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(GuncelleButonu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SanatciAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SanatciUlkesiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SilButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(AdminAdiAlani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addComponent(SanatciArama))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GeriButonu)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SanatciUlkesiAlani)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EkleButonu)
                            .addComponent(GuncelleButonu)
                            .addComponent(SilButonu))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SanatciAdiAlani))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdminAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(SanatciArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SanatciAdiAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanatciAdiAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SanatciAdiAlaniActionPerformed

    private void SanatciAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanatciAramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SanatciAramaActionPerformed

    private void SanatciTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanatciTablosuMouseClicked
        // TODO add your handling code here:
        int selectedrow = SanatciTablosu.getSelectedRow();
        
        SanatciAdiAlani.setText(modelSanatci.getValueAt(selectedrow, 1).toString());
        SanatciUlkesiAlani.setText(modelSanatci.getValueAt(selectedrow, 2).toString());
    }//GEN-LAST:event_SanatciTablosuMouseClicked

    private void GeriButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriButonuActionPerformed
        // TODO add your handling code here:
        Giris_Paneli giris = new Giris_Paneli();
        
        Admin_Paneli adminPaneli = new Admin_Paneli(giris, true);
        setVisible(false);
            
        adminPaneli.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_GeriButonuActionPerformed

    private void EkleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleButonuActionPerformed
        // TODO add your handling code here:
        String sanatciAd  =  SanatciAdiAlani.getText();
        String sanatciTarih = SanatciUlkesiAlani.getText();
        
        adminSanatciIslemleri.SanatciEkle(sanatciAd, sanatciTarih);
        
        Sanatcilari_Goruntule();
    }//GEN-LAST:event_EkleButonuActionPerformed

    private void GuncelleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuncelleButonuActionPerformed
        // TODO add your handling code here:
        String sarkiAd  =  SanatciAdiAlani.getText();
        String sarkiTarih = SanatciUlkesiAlani.getText();
        
        int selectedrow = SanatciTablosu.getSelectedRow();
        
        if(selectedrow != -1) {
            int id = (int) modelSanatci.getValueAt(selectedrow, 0);
            adminSanatciIslemleri.SanatciGuncelle(id, sarkiAd, sarkiTarih);
            Sanatcilari_Goruntule();
        }
    }//GEN-LAST:event_GuncelleButonuActionPerformed

    private void SilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilButonuActionPerformed
        // TODO add your handling code here:
        String sarkiAd  =  SanatciAdiAlani.getText();
        String sarkiTarih = SanatciUlkesiAlani.getText();
        
        int selectedrow = SanatciTablosu.getSelectedRow();
        
        if(selectedrow != -1) {
            int id = (int) modelSanatci.getValueAt(selectedrow, 0);
            adminSanatciIslemleri.SanatciSil(id);
            Sanatcilari_Goruntule();
        }
    }//GEN-LAST:event_SilButonuActionPerformed

    private void SanatciAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SanatciAramaKeyReleased
        // TODO add your handling code here:
        String ara = SanatciArama.getText();
        
        Sanatci_Dinamik_Ara(ara);
    }//GEN-LAST:event_SanatciAramaKeyReleased

    public void Sanatcilari_Goruntule() {
        
        modelSanatci.setRowCount(0);
        
        ArrayList<Sanatci> sanatcilar = new ArrayList<Sanatci>();
        
        sanatcilar = adminSanatciIslemleri.SanatcilariGetir();
        
        if (sanatcilar != null ) {
            
            for (Sanatci sanatci : sanatcilar) {
                Object[] eklenecek = {sanatci.getSanatciID(), sanatci.getSanatciAd(), sanatci.getSanatciUlke()};
                
                modelSanatci.addRow(eklenecek);
            }
        }
    }
    
    public void Sanatci_Dinamik_Ara(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelSanatci);
        
        SanatciTablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Sanatci_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Sanatci_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Sanatci_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Sanatci_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin_Sanatci_Paneli dialog = new Admin_Sanatci_Paneli(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminAdiAlani;
    private javax.swing.JButton EkleButonu;
    private javax.swing.JButton GeriButonu;
    private javax.swing.JButton GuncelleButonu;
    private javax.swing.JTextField SanatciAdiAlani;
    private javax.swing.JTextField SanatciArama;
    private javax.swing.JTable SanatciTablosu;
    private javax.swing.JTextField SanatciUlkesiAlani;
    private javax.swing.JButton SilButonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
