
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranadudukabak
 */
public class Admin_Top_10_Listeleri extends javax.swing.JDialog {

    DefaultTableModel modelDinlenmeSayisi;
    DefaultTableModel modelKlasikDinlenmeSayisi;
    DefaultTableModel modelJazzDinlenmeSayisi;
    DefaultTableModel modelPopDinlenmeSayisi;
    
    Admin_Top_10_Islemleri top10Islemleri = new Admin_Top_10_Islemleri();
    /**
     * Creates new form Top_10_Listeleri
     */
    public Admin_Top_10_Listeleri(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        modelDinlenmeSayisi = (DefaultTableModel) DinlenmeSayisiSarkiTablosu.getModel();
        Dinlenme_Sayisi_Top_10_Goruntule();
        
        modelKlasikDinlenmeSayisi = (DefaultTableModel) KlasikDinlenmeSayisiSarkiTablosu.getModel();
        Klasik_Dinlenme_Sayisi_Top_10_Goruntule();
        
        modelJazzDinlenmeSayisi = (DefaultTableModel) JazzDinlenmeSayisiSarkiTablosu.getModel();
        Jazz_Dinlenme_Sayisi_Top_10_Goruntule();
//        
        modelPopDinlenmeSayisi = (DefaultTableModel) PopDinlenmeSayisiSarkiTablosu.getModel();
        Pop_Dinlenme_Sayisi_Top_10_Goruntule();
        
         String kullanici_adi  = Giris_Paneli.kullanici_adi;
        AdminAdi.setText(kullanici_adi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        DinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        KlasikDinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        JazzDinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        PopDinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        UlkeDinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        GeriButonu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AdminAdi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        DinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(DinlenmeSayisiSarkiTablosu);

        KlasikDinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KlasikDinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlasikDinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(KlasikDinlenmeSayisiSarkiTablosu);

        JazzDinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JazzDinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JazzDinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(JazzDinlenmeSayisiSarkiTablosu);

        PopDinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PopDinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopDinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(PopDinlenmeSayisiSarkiTablosu);

        UlkeDinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UlkeDinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UlkeDinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(UlkeDinlenmeSayisiSarkiTablosu);

        GeriButonu.setText("<-");
        GeriButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriButonuActionPerformed(evt);
            }
        });

        jLabel1.setText("Admin:");

        jLabel3.setText("**********************************KLASİK ŞARKILAR TOP 10 LİSTESİ********************************");

        jLabel4.setText("**********************************JAZZ ŞARKILAR TOP 10 LİSTESİ**********************************");

        jLabel5.setText("**********************************POP ŞARKILAR TOP 10 LİSTESİ***********************************");

        jLabel6.setText("***************************GENEL DİNLENME SAYISINA GÖRE TOP 10 LİSTESİ***************************");

        jLabel7.setText("************************************ÜLKELERE GÖRE TOP 10 LİSTESİ************************************");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeriButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(638, 638, 638)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdminAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeriButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdminAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
//        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
//
//        SarkiAdiAlani.setText(modelKlasik.getValueAt(selectedrow, 1).toString());
//        SarkiTarihiAlani.setText(modelKlasik.getValueAt(selectedrow, 2).toString());
//        SarkiSanatciAlani.setText(modelKlasik.getValueAt(selectedrow, 3).toString());
//        SarkiAlbumAlani.setText(modelKlasik.getValueAt(selectedrow, 4).toString());
//        SarkiTurAlani.setText(modelKlasik.getValueAt(selectedrow, 5).toString());
//        SarkiSureAlani.setText(modelKlasik.getValueAt(selectedrow, 6).toString());
//        SarkiDinlenmeSayisiAlani.setText(modelKlasik.getValueAt(selectedrow, 7).toString());
    }//GEN-LAST:event_DinlenmeSayisiSarkiTablosuMouseClicked

    private void KlasikDinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlasikDinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KlasikDinlenmeSayisiSarkiTablosuMouseClicked

    private void JazzDinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JazzDinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JazzDinlenmeSayisiSarkiTablosuMouseClicked

    private void PopDinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopDinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PopDinlenmeSayisiSarkiTablosuMouseClicked

    private void UlkeDinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UlkeDinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UlkeDinlenmeSayisiSarkiTablosuMouseClicked

    private void GeriButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriButonuActionPerformed
        // TODO add your handling code here:
              Giris_Paneli giris = new Giris_Paneli();
        
        Admin_Paneli adminPaneli = new Admin_Paneli(giris, true);
        setVisible(false);
            
        adminPaneli.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_GeriButonuActionPerformed

    
    public void Dinlenme_Sayisi_Top_10_Goruntule() {
        
        modelDinlenmeSayisi.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = top10Islemleri.DinlenmeSayisiTop10Getir();
        
        //if (sarkilar != null ) {
        //for () {
            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
                
                modelDinlenmeSayisi.addRow(eklenecek);
            }
        //}
        //}
    }
    
    public void Klasik_Dinlenme_Sayisi_Top_10_Goruntule() {
        
        modelKlasikDinlenmeSayisi.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = top10Islemleri.KlasikDinlenmeSayisiTop10Getir();
        
        //if (sarkilar != null ) {
        //for () {
            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
                
                modelKlasikDinlenmeSayisi.addRow(eklenecek);
            }
        //}
        //}
    }
    
    public void Jazz_Dinlenme_Sayisi_Top_10_Goruntule() {
        
        modelJazzDinlenmeSayisi.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = top10Islemleri.JazzDinlenmeSayisiTop10Getir();
        
        //if (sarkilar != null ) {
        //for () {
            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
                
                modelJazzDinlenmeSayisi.addRow(eklenecek);
            }
        //}
        //}
    }
    
    public void Pop_Dinlenme_Sayisi_Top_10_Goruntule() {
        
        modelPopDinlenmeSayisi.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = top10Islemleri.PopDinlenmeSayisiTop10Getir();
        
        //if (sarkilar != null ) {
        //for () {
            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
                
                modelPopDinlenmeSayisi.addRow(eklenecek);
            }
        //}
        //}
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Top_10_Listeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Top_10_Listeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Top_10_Listeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Top_10_Listeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin_Top_10_Listeleri dialog = new Admin_Top_10_Listeleri(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminAdi;
    private javax.swing.JTable DinlenmeSayisiSarkiTablosu;
    private javax.swing.JButton GeriButonu;
    private javax.swing.JTable JazzDinlenmeSayisiSarkiTablosu;
    private javax.swing.JTable KlasikDinlenmeSayisiSarkiTablosu;
    private javax.swing.JTable PopDinlenmeSayisiSarkiTablosu;
    private javax.swing.JTable UlkeDinlenmeSayisiSarkiTablosu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
