

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranadudukabak
 */
public class Giris_Paneli extends javax.swing.JFrame {
    
    public static String kullanici_adi;
    public static String  normal_kullanici_adi ;
    public static String premium_kullanici_adi ;
    Admin_Muzik_Islemleri adminIslemleri = new Admin_Muzik_Islemleri();
    Normal_Kullanici_Islemleri normalKullaniciIslemleri = new Normal_Kullanici_Islemleri();
    Premium_Kullanici_Islemleri premiumKullaniciIslemleri = new Premium_Kullanici_Islemleri();
    /**
     * Creates new form Giris_Paneli
     */
    public Giris_Paneli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmailAlani = new javax.swing.JTextField();
        SifreAlani = new javax.swing.JPasswordField();
        NormalKullaniciGiris = new javax.swing.JButton();
        AdminGiris = new javax.swing.JButton();
        PremiumKullaniciGiris = new javax.swing.JButton();
        MesajYazisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email:");

        jLabel2.setText("Şifre:");

        NormalKullaniciGiris.setText("Normal Kullanıcı Giriş");
        NormalKullaniciGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalKullaniciGirisActionPerformed(evt);
            }
        });

        AdminGiris.setText("Admin Giriş");
        AdminGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminGirisActionPerformed(evt);
            }
        });

        PremiumKullaniciGiris.setText("Premium Kullanıcı Giriş ");
        PremiumKullaniciGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumKullaniciGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MesajYazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmailAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(SifreAlani))))
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(NormalKullaniciGiris)
                .addGap(85, 85, 85)
                .addComponent(AdminGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PremiumKullaniciGiris)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmailAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SifreAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(MesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NormalKullaniciGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PremiumKullaniciGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminGirisActionPerformed
        // TODO add your handling code here:
        MesajYazisi.setText("");
        
        kullanici_adi = EmailAlani.getText();
        String parola = new String(SifreAlani.getPassword());
        
        boolean girisbasarili = adminIslemleri.GirisYap(kullanici_adi, parola);
        
        if(girisbasarili) {
            
            Admin_Paneli adminPaneli = new Admin_Paneli(this, true);
            setVisible(false);
            
            adminPaneli.setVisible(true);
            System.exit(0);
        }
        else {
            
            MesajYazisi.setText("Giriş başarısız. Lütfen tekrar deneyin.");
        }
    }//GEN-LAST:event_AdminGirisActionPerformed

    private void NormalKullaniciGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalKullaniciGirisActionPerformed
        // TODO add your handling code here:
        MesajYazisi.setText("");
        
        normal_kullanici_adi = EmailAlani.getText();
        String parola = new String(SifreAlani.getPassword());
        
        boolean girisbasarili = normalKullaniciIslemleri.GirisYap(normal_kullanici_adi, parola);
        
        if(girisbasarili) {
            
            Normal_Kullanici_Paneli normalKullaniciPaneli = new Normal_Kullanici_Paneli(this, true);
            setVisible(false);
            
            normalKullaniciPaneli.setVisible(true);
            System.exit(0);
        }
        else {
            
            MesajYazisi.setText("Giriş başarısız. Lütfen tekrar deneyin.");
        }
    }//GEN-LAST:event_NormalKullaniciGirisActionPerformed

    private void PremiumKullaniciGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumKullaniciGirisActionPerformed
        // TODO add your handling code here:
        MesajYazisi.setText("");
        
         premium_kullanici_adi = EmailAlani.getText();
        String parola = new String(SifreAlani.getPassword());
        
        boolean girisbasarili = premiumKullaniciIslemleri.GirisYap(premium_kullanici_adi, parola);
        
        if(girisbasarili) {
            
            Premium_Kullanici_Paneli premiumKullaniciPaneli = new Premium_Kullanici_Paneli(this, true);
            setVisible(false);
            
            premiumKullaniciPaneli.setVisible(true);
            System.exit(0);
        }
        else {
            
            MesajYazisi.setText("Giriş başarısız. Lütfen tekrar deneyin.");
        }
    }//GEN-LAST:event_PremiumKullaniciGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris_Paneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris_Paneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminGiris;
    private javax.swing.JTextField EmailAlani;
    private javax.swing.JLabel MesajYazisi;
    private javax.swing.JButton NormalKullaniciGiris;
    private javax.swing.JButton PremiumKullaniciGiris;
    private javax.swing.JPasswordField SifreAlani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
