
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranadudukabak
 */
public class Kullanici_Top_10_Listeleri2 extends javax.swing.JDialog {

    DefaultTableModel modelDinlenmeSayisi;
    DefaultTableModel modelKlasikDinlenmeSayisi;
    DefaultTableModel modelJazzDinlenmeSayisi;
    DefaultTableModel modelPopDinlenmeSayisi;
    DefaultTableModel modelUlkeDinlenmeSayisi;
    
    Kullanici_Top_10_Islemleri kullaniciTop10Islemleri = new Kullanici_Top_10_Islemleri();
    private JComboBox comboBox = new JComboBox();
    //JComboBox ulkeComboBox;
    
    String kullanici_adi  = Giris_Paneli.kullanici_adi;
    
    /**
     * Creates new form Admin_Top_10_Listeleri
     */
    public Kullanici_Top_10_Listeleri2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        modelDinlenmeSayisi = (DefaultTableModel) DinlenmeSayisiSarkiTablosu.getModel();
        Dinlenme_Sayisi_Top_10_Goruntule();
        
        modelKlasikDinlenmeSayisi = (DefaultTableModel) KlasikDinlenmeSayisiSarkiTablosu.getModel();
        Klasik_Dinlenme_Sayisi_Top_10_Goruntule();
        
        modelJazzDinlenmeSayisi = (DefaultTableModel) JazzDinlenmeSayisiSarkiTablosu.getModel();
        Jazz_Dinlenme_Sayisi_Top_10_Goruntule();
        
        modelPopDinlenmeSayisi = (DefaultTableModel) PopDinlenmeSayisiSarkiTablosu.getModel();
        Pop_Dinlenme_Sayisi_Top_10_Goruntule();
        
        modelUlkeDinlenmeSayisi = (DefaultTableModel) UlkeDinlenmeSayisiSarkiTablosu.getModel();
//        Ulke_Dinlenme_Sayisi_Top_10_Goruntule();

        KullaniciAdiAlani.setText(kullanici_adi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        DinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        KlasikDinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        JazzDinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        PopDinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        UlkeDinlenmeSayisiSarkiTablosu = new javax.swing.JTable();
        GeriButonu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        KullaniciAdiAlani = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        KlasikEkle = new javax.swing.JButton();
        KlasikSil = new javax.swing.JButton();
        JazzEkle = new javax.swing.JButton();
        JazzSil = new javax.swing.JButton();
        PopEkle = new javax.swing.JButton();
        PopSil = new javax.swing.JButton();
        DinlenmeSayisinaGoreEkle = new javax.swing.JButton();
        DinlenmeSayisinaGoreSil = new javax.swing.JButton();
        UlkelereGoreEkle = new javax.swing.JButton();
        UlkelereGoreSil = new javax.swing.JButton();
        UlkeComboBox = new javax.swing.JComboBox<>();
        UlkeSecimButonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        DinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(DinlenmeSayisiSarkiTablosu);

        KlasikDinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KlasikDinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlasikDinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(KlasikDinlenmeSayisiSarkiTablosu);

        JazzDinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JazzDinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JazzDinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(JazzDinlenmeSayisiSarkiTablosu);

        PopDinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PopDinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopDinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(PopDinlenmeSayisiSarkiTablosu);

        UlkeDinlenmeSayisiSarkiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ad", "Şarkı Tarih", "Şarkı Sanatçı", "Şarkı Albüm", "Şarkı Tür", "Şarkı Süre", "Şarkı Dinlenme Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UlkeDinlenmeSayisiSarkiTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UlkeDinlenmeSayisiSarkiTablosuMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(UlkeDinlenmeSayisiSarkiTablosu);

        GeriButonu.setText("<-");
        GeriButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriButonuActionPerformed(evt);
            }
        });

        jLabel1.setText("Kullanıcı Adı");

        jLabel3.setText("**********************************KLASİK ŞARKILAR TOP 10 LİSTESİ********************************");

        jLabel4.setText("**********************************JAZZ ŞARKILAR TOP 10 LİSTESİ**********************************");

        jLabel5.setText("**********************************POP ŞARKILAR TOP 10 LİSTESİ***********************************");

        jLabel6.setText("***************************GENEL DİNLENME SAYISINA GÖRE TOP 10 LİSTESİ***************************");

        jLabel7.setText("************************************ÜLKELERE GÖRE TOP 10 LİSTESİ************************************");

        KlasikEkle.setText("EKLE");
        KlasikEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlasikEkleActionPerformed(evt);
            }
        });

        KlasikSil.setText("SİL");
        KlasikSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlasikSilActionPerformed(evt);
            }
        });

        JazzEkle.setText("EKLE");
        JazzEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JazzEkleActionPerformed(evt);
            }
        });

        JazzSil.setText("SİL");
        JazzSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JazzSilActionPerformed(evt);
            }
        });

        PopEkle.setText("EKLE");
        PopEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopEkleActionPerformed(evt);
            }
        });

        PopSil.setText("SİL");
        PopSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopSilActionPerformed(evt);
            }
        });

        DinlenmeSayisinaGoreEkle.setText("EKLE");
        DinlenmeSayisinaGoreEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DinlenmeSayisinaGoreEkleActionPerformed(evt);
            }
        });

        DinlenmeSayisinaGoreSil.setText("SİL");
        DinlenmeSayisinaGoreSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DinlenmeSayisinaGoreSilActionPerformed(evt);
            }
        });

        UlkelereGoreEkle.setText("EKLE");
        UlkelereGoreEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlkelereGoreEkleActionPerformed(evt);
            }
        });

        UlkelereGoreSil.setText("SİL");
        UlkelereGoreSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlkelereGoreSilActionPerformed(evt);
            }
        });

        UlkeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lütfen Ülke Seçiniz", "Türkiye", "Almanya", "İngiltere", "Amerika" }));

        UlkeSecimButonu.setText("SEÇ");
        UlkeSecimButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlkeSecimButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeriButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(638, 638, 638)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KullaniciAdiAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PopEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PopSil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KlasikEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(KlasikSil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JazzEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JazzSil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DinlenmeSayisinaGoreEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DinlenmeSayisinaGoreSil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UlkelereGoreEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UlkelereGoreSil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UlkeComboBox, 0, 0, Short.MAX_VALUE)
                            .addComponent(UlkeSecimButonu, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GeriButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KullaniciAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KlasikEkle)
                            .addComponent(KlasikSil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JazzEkle)
                            .addComponent(JazzSil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PopEkle)
                            .addComponent(PopSil))
                        .addGap(150, 150, 150))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(UlkeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UlkeSecimButonu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DinlenmeSayisinaGoreEkle)
                    .addComponent(DinlenmeSayisinaGoreSil))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UlkelereGoreEkle)
                    .addComponent(UlkelereGoreSil))
                .addGap(231, 231, 231))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
//        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
//
//        SarkiAdiAlani.setText(modelKlasik.getValueAt(selectedrow, 1).toString());
//        SarkiTarihiAlani.setText(modelKlasik.getValueAt(selectedrow, 2).toString());
//        SarkiSanatciAlani.setText(modelKlasik.getValueAt(selectedrow, 3).toString());
//        SarkiAlbumAlani.setText(modelKlasik.getValueAt(selectedrow, 4).toString());
//        SarkiTurAlani.setText(modelKlasik.getValueAt(selectedrow, 5).toString());
//        SarkiSureAlani.setText(modelKlasik.getValueAt(selectedrow, 6).toString());
//        SarkiDinlenmeSayisiAlani.setText(modelKlasik.getValueAt(selectedrow, 7).toString());
    }//GEN-LAST:event_DinlenmeSayisiSarkiTablosuMouseClicked

    private void KlasikDinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlasikDinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KlasikDinlenmeSayisiSarkiTablosuMouseClicked

    private void JazzDinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JazzDinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JazzDinlenmeSayisiSarkiTablosuMouseClicked

    private void PopDinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopDinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PopDinlenmeSayisiSarkiTablosuMouseClicked

    private void UlkeDinlenmeSayisiSarkiTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UlkeDinlenmeSayisiSarkiTablosuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UlkeDinlenmeSayisiSarkiTablosuMouseClicked

    private void KlasikEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlasikEkleActionPerformed
        // TODO add your handling code here:
//        int selectedrow = KlasikDinlenmeSayisiSarkiTablosu.getSelectedRow();
//        
//        String sarkiAd = modelKlasikDinlenmeSayisi.getValueAt(selectedrow, 1).toString();
//        String sarkiTarih = modelKlasikDinlenmeSayisi.getValueAt(selectedrow, 2).toString();
//        String sarkiSanatci = modelKlasikDinlenmeSayisi.getValueAt(selectedrow, 3).toString();
//        String sarkiAlbum = modelKlasikDinlenmeSayisi.getValueAt(selectedrow, 4).toString();
//        String sarkiTur = modelKlasikDinlenmeSayisi.getValueAt(selectedrow, 5).toString();
//        String sarkiSure = modelKlasikDinlenmeSayisi.getValueAt(selectedrow, 6).toString();
//        String sarkiDinlenmeSayisi = modelKlasikDinlenmeSayisi.getValueAt(selectedrow, 7).toString();
//        
//        kullaniciTop10Islemleri.KlasikMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
//        
//        Klasik_Dinlenme_Sayisi_Top_10_Goruntule();
    }//GEN-LAST:event_KlasikEkleActionPerformed

    private void KlasikSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlasikSilActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        
        int selectedrow = KlasikDinlenmeSayisiSarkiTablosu.getSelectedRow();
        
        if(selectedrow != -1) {
            int id = (int) modelKlasikDinlenmeSayisi.getValueAt(selectedrow, 0);
//            kullaniciTop10Islemleri.KlasikMuzikSil(id);
            Klasik_Dinlenme_Sayisi_Top_10_Goruntule();
        }
    }//GEN-LAST:event_KlasikSilActionPerformed

    private void GeriButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriButonuActionPerformed
        // TODO add your handling code here:
                      Giris_Paneli giris = new Giris_Paneli();
        Premium_Kullanici_Paneli kullaniciPaneli = new Premium_Kullanici_Paneli(giris, true);
        setVisible(false);
            
        kullaniciPaneli.setVisible(true);
        System.exit(0);
            
 
        
    }//GEN-LAST:event_GeriButonuActionPerformed

    private void JazzEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JazzEkleActionPerformed
        // TODO add your handling code here:
        int selectedrow = JazzDinlenmeSayisiSarkiTablosu.getSelectedRow();
        
        String sarkiAd = modelJazzDinlenmeSayisi.getValueAt(selectedrow, 1).toString();
        String sarkiTarih = modelJazzDinlenmeSayisi.getValueAt(selectedrow, 2).toString();
        String sarkiSanatci = modelJazzDinlenmeSayisi.getValueAt(selectedrow, 3).toString();
        String sarkiAlbum = modelJazzDinlenmeSayisi.getValueAt(selectedrow, 4).toString();
        String sarkiTur = modelJazzDinlenmeSayisi.getValueAt(selectedrow, 5).toString();
        String sarkiSure = modelJazzDinlenmeSayisi.getValueAt(selectedrow, 6).toString();
        String sarkiDinlenmeSayisi = modelJazzDinlenmeSayisi.getValueAt(selectedrow, 7).toString();
        
//        kullaniciTop10Islemleri.JazzMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
        
        Jazz_Dinlenme_Sayisi_Top_10_Goruntule();
    }//GEN-LAST:event_JazzEkleActionPerformed

    private void JazzSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JazzSilActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        
        int selectedrow = JazzDinlenmeSayisiSarkiTablosu.getSelectedRow();
        
        if(selectedrow != -1) {
            int id = (int) modelJazzDinlenmeSayisi.getValueAt(selectedrow, 0);
//            kullaniciTop10Islemleri.JazzMuzikSil(id);
            Jazz_Dinlenme_Sayisi_Top_10_Goruntule();
        }
    }//GEN-LAST:event_JazzSilActionPerformed

    private void PopEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopEkleActionPerformed
        // TODO add your handling code here:
        int selectedrow = PopDinlenmeSayisiSarkiTablosu.getSelectedRow();
        
        String sarkiAd = modelPopDinlenmeSayisi.getValueAt(selectedrow, 1).toString();
        String sarkiTarih = modelPopDinlenmeSayisi.getValueAt(selectedrow, 2).toString();
        String sarkiSanatci = modelPopDinlenmeSayisi.getValueAt(selectedrow, 3).toString();
        String sarkiAlbum = modelPopDinlenmeSayisi.getValueAt(selectedrow, 4).toString();
        String sarkiTur = modelPopDinlenmeSayisi.getValueAt(selectedrow, 5).toString();
        String sarkiSure = modelPopDinlenmeSayisi.getValueAt(selectedrow, 6).toString();
        String sarkiDinlenmeSayisi = modelPopDinlenmeSayisi.getValueAt(selectedrow, 7).toString();
        
//        kullaniciTop10Islemleri.PopMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
        
        Pop_Dinlenme_Sayisi_Top_10_Goruntule();
    }//GEN-LAST:event_PopEkleActionPerformed

    private void PopSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopSilActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        
        int selectedrow = PopDinlenmeSayisiSarkiTablosu.getSelectedRow();
        
        if(selectedrow != -1) {
            int id = (int) modelPopDinlenmeSayisi.getValueAt(selectedrow, 0);
//            kullaniciTop10Islemleri.PopMuzikSil(id);
            Pop_Dinlenme_Sayisi_Top_10_Goruntule();
        }
    }//GEN-LAST:event_PopSilActionPerformed

    private void DinlenmeSayisinaGoreEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinlenmeSayisinaGoreEkleActionPerformed
        // TODO add your handling code here:
        int selectedrow = DinlenmeSayisiSarkiTablosu.getSelectedRow();
        
        String sarkiAd = modelDinlenmeSayisi.getValueAt(selectedrow, 1).toString();
        String sarkiTarih = modelDinlenmeSayisi.getValueAt(selectedrow, 2).toString();
        String sarkiSanatci = modelDinlenmeSayisi.getValueAt(selectedrow, 3).toString();
        String sarkiAlbum = modelDinlenmeSayisi.getValueAt(selectedrow, 4).toString();
        String sarkiTur = modelDinlenmeSayisi.getValueAt(selectedrow, 5).toString();
        String sarkiSure = modelDinlenmeSayisi.getValueAt(selectedrow, 6).toString();
        String sarkiDinlenmeSayisi = modelDinlenmeSayisi.getValueAt(selectedrow, 7).toString();
        
        if(kullanici_adi.equalsIgnoreCase("gamze_dinç")) {

            kullaniciTop10Islemleri.gamzeKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
        } else if (kullanici_adi.equalsIgnoreCase("etkacure@gmail.com")) {

            kullaniciTop10Islemleri.etkaKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
        } else if (kullanici_adi.equalsIgnoreCase("melisayilmaz@gmail.com")) {

            kullaniciTop10Islemleri.melisaKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
        } else if (kullanici_adi.equalsIgnoreCase("furkanyavuz@gmail.com")) {

            kullaniciTop10Islemleri.furkanKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
        }
        if (kullanici_adi.equalsIgnoreCase("muratgunduz@gmail.com")) {

            kullaniciTop10Islemleri.muratKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);
        }
        if(kullanici_adi.equalsIgnoreCase("okandemir@gmail.com")){

            kullaniciTop10Islemleri.okanKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);             }
        else if(kullanici_adi.equalsIgnoreCase("onuraksoy@gmail.com")){

            kullaniciTop10Islemleri.onurKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);             }
        else if(kullanici_adi.equalsIgnoreCase("serrasevvalkabak@gmail.com")){

            kullaniciTop10Islemleri.serraKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);             }
        else if(kullanici_adi.equalsIgnoreCase("sezenkaya@gmail.com")){

            kullaniciTop10Islemleri.sezenKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);             }
        if(kullanici_adi.equalsIgnoreCase("zehracelik@gmail.com")){

            kullaniciTop10Islemleri.zehraKullaniciFavorilereMuzikEkle(sarkiAd, sarkiTarih, sarkiSanatci, sarkiAlbum, sarkiTur, sarkiSure, sarkiDinlenmeSayisi);  
        }  
        
        Dinlenme_Sayisi_Top_10_Goruntule();
        
    }//GEN-LAST:event_DinlenmeSayisinaGoreEkleActionPerformed

    private void DinlenmeSayisinaGoreSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinlenmeSayisinaGoreSilActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        
        int selectedrow = DinlenmeSayisiSarkiTablosu.getSelectedRow();
        
        if(selectedrow != -1) {
            flag = 1;
        }
        if(kullanici_adi.equalsIgnoreCase("gamze_dinç")){
//        int flag = 0;
//        
//        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
//        int selectedrow2 = JazzSarkiTablosu.getSelectedRow();
//        int selectedrow3 = PopSarkiTablosu.getSelectedRow();
//        
//        if(selectedrow != -1) {
//            flag = 1;
//        } else if(selectedrow2 != -1) {
//            flag = 2;
//        } else if(selectedrow3 != -1){
//            flag = 3;
//        }
        
        if(flag == 1) {
            int id = (int) modelDinlenmeSayisi.getValueAt(selectedrow, 0);
            kullaniciTop10Islemleri.gamzeKullaniciMuzikSil(id);
//            Kullanici_Klasik_Muzikleri_Goruntule();
        } /*else if(flag == 2) {
            int id2 = (int) modelJazz.getValueAt(selectedrow2, 0);
            normalKullaniciIslemleri.gamzeKullaniciMuzikSil(id2);
//            Kullanici_Jazz_Muzikleri_Goruntule(); 
        } else if(flag == 3) {
            int id3 = (int) modelPop.getValueAt(selectedrow3, 0);
            normalKullaniciIslemleri.gamzeKullaniciMuzikSil(id3);
//            Kullanici_Pop_Muzikleri_Goruntule(); 
        }*/
        }
        
        ////////////////////////////////////////////
          else if(kullanici_adi.equalsIgnoreCase("etkacure@gmail.com")){
//        int flag = 0;
//        
//        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
//        int selectedrow2 = JazzSarkiTablosu.getSelectedRow();
//        int selectedrow3 = PopSarkiTablosu.getSelectedRow();
        
//        if(selectedrow != -1) {
//            flag = 1;
//        } else if(selectedrow2 != -1) {
//            flag = 2;
//        } else if(selectedrow3 != -1){
//            flag = 3;
//        }
//        
        if(flag == 1) {
            int id = (int) modelDinlenmeSayisi.getValueAt(selectedrow, 0);
            kullaniciTop10Islemleri.etkaKullaniciMuzikSil(id);
//            Kullanici_Klasik_Muzikleri_Goruntule();
        } //else if(flag == 2) {
//            int id2 = (int) modelJazz.getValueAt(selectedrow2, 0);
//            normalKullaniciIslemleri.etkaKullaniciMuzikSil(id2);
//            Kullanici_Jazz_Muzikleri_Goruntule(); 
//        } else if(flag == 3) {
//            int id3 = (int) modelPop.getValueAt(selectedrow3, 0);
//            normalKullaniciIslemleri.etkaKullaniciMuzikSil(id3);
//            Kullanici_Pop_Muzikleri_Goruntule(); 
//        }
        }
                
         ///////////////
          else if(kullanici_adi.equalsIgnoreCase("melisayilmaz@gmail.com")){
//        int flag = 0;
//        
//        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
//        int selectedrow2 = JazzSarkiTablosu.getSelectedRow();
//        int selectedrow3 = PopSarkiTablosu.getSelectedRow();
//        
//        if(selectedrow != -1) {
//            flag = 1;
//        } else if(selectedrow2 != -1) {
//            flag = 2;
//        } else if(selectedrow3 != -1){
//            flag = 3;
//        }
//        
        if(flag == 1) {
            int id = (int) modelDinlenmeSayisi.getValueAt(selectedrow, 0);
            kullaniciTop10Islemleri.melisaKullaniciMuzikSil(id);
//            Kullanici_Klasik_Muzikleri_Goruntule();
        } //else if(flag == 2) {
//            int id2 = (int) modelJazz.getValueAt(selectedrow2, 0);
//            normalKullaniciIslemleri.melisaKullaniciMuzikSil(id2);
//            Kullanici_Jazz_Muzikleri_Goruntule(); 
//        } else if(flag == 3) {
//            int id3 = (int) modelPop.getValueAt(selectedrow3, 0);
//            normalKullaniciIslemleri.melisaKullaniciMuzikSil(id3);
//            Kullanici_Pop_Muzikleri_Goruntule(); 
//        }
        }
                 //////////////////////
                     else    if(kullanici_adi.equalsIgnoreCase("furkanyavuz@gmail.com")){
//        int flag = 0;
//        
//        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
//        int selectedrow2 = JazzSarkiTablosu.getSelectedRow();
//        int selectedrow3 = PopSarkiTablosu.getSelectedRow();
//        
//        if(selectedrow != -1) {
//            flag = 1;
//        } else if(selectedrow2 != -1) {
//            flag = 2;
//        } else if(selectedrow3 != -1){
//            flag = 3;
//        }
        
        if(flag == 1) {
            int id = (int) modelDinlenmeSayisi.getValueAt(selectedrow, 0);
            kullaniciTop10Islemleri.furkanKullaniciMuzikSil(id);
//            Kullanici_Klasik_Muzikleri_Goruntule();
        } //else if(flag == 2) {
//            int id2 = (int) modelJazz.getValueAt(selectedrow2, 0);
//            normalKullaniciIslemleri.furkanKullaniciMuzikSil(id2);
//            Kullanici_Jazz_Muzikleri_Goruntule(); 
//        } else if(flag == 3) {
//            int id3 = (int) modelPop.getValueAt(selectedrow3, 0);
//            normalKullaniciIslemleri.furkanKullaniciMuzikSil(id3);
//            Kullanici_Pop_Muzikleri_Goruntule(); 
//        }
        }
                         ////////////
        else if(kullanici_adi.equalsIgnoreCase("muratgunduz@gmail.com")){
//        int flag = 0;
//        
//        int selectedrow = KlasikSarkiTablosu.getSelectedRow();
//        int selectedrow2 = JazzSarkiTablosu.getSelectedRow();
//        int selectedrow3 = PopSarkiTablosu.getSelectedRow();
//        
//        if(selectedrow != -1) {
//            flag = 1;
//        } else if(selectedrow2 != -1) {
//            flag = 2;
//        } else if(selectedrow3 != -1){
//            flag = 3;
//        }
        
        if(flag == 1) {
            int id = (int) modelDinlenmeSayisi.getValueAt(selectedrow, 0);
            kullaniciTop10Islemleri.muratKullaniciMuzikSil(id);
//            Kullanici_Klasik_Muzikleri_Goruntule();
//        } else if(flag == 2) {
//            int id2 = (int) modelJazz.getValueAt(selectedrow2, 0);
//            normalKullaniciIslemleri.muratKullaniciMuzikSil(id2);
//            Kullanici_Jazz_Muzikleri_Goruntule(); 
//        } else if(flag == 3) {
//            int id3 = (int) modelPop.getValueAt(selectedrow3, 0);
//            normalKullaniciIslemleri.muratKullaniciMuzikSil(id3);
//            Kullanici_Pop_Muzikleri_Goruntule(); 
//        }
        }
          
        }
    }//GEN-LAST:event_DinlenmeSayisinaGoreSilActionPerformed

    private void UlkelereGoreEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlkelereGoreEkleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UlkelereGoreEkleActionPerformed

    private void UlkelereGoreSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlkelereGoreSilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UlkelereGoreSilActionPerformed

    private void UlkeSecimButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlkeSecimButonuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UlkeSecimButonuActionPerformed

    public void Dinlenme_Sayisi_Top_10_Goruntule() {
        
        modelDinlenmeSayisi.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = kullaniciTop10Islemleri.DinlenmeSayisiTop10Getir();
        
        //if (sarkilar != null ) {
        //for () {
            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
                
                modelDinlenmeSayisi.addRow(eklenecek);
            }
        //}
        //}
    }
    
    public void Klasik_Dinlenme_Sayisi_Top_10_Goruntule() {
        
        modelKlasikDinlenmeSayisi.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = kullaniciTop10Islemleri.KlasikDinlenmeSayisiTop10Getir();
        
        //if (sarkilar != null ) {
        //for () {
            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
                
                modelKlasikDinlenmeSayisi.addRow(eklenecek);
            }
        //}
        //}
    }
    
    public void Jazz_Dinlenme_Sayisi_Top_10_Goruntule() {
        
        modelJazzDinlenmeSayisi.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = kullaniciTop10Islemleri.JazzDinlenmeSayisiTop10Getir();
        
        //if (sarkilar != null ) {
        //for () {
            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
                
                modelJazzDinlenmeSayisi.addRow(eklenecek);
            }
        //}
        //}
    }
    
    public void Pop_Dinlenme_Sayisi_Top_10_Goruntule() {
        
        modelPopDinlenmeSayisi.setRowCount(0);
        
        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
        
        sarkilar = kullaniciTop10Islemleri.PopDinlenmeSayisiTop10Getir();
        
        //if (sarkilar != null ) {
        //for () {
            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
                
                modelPopDinlenmeSayisi.addRow(eklenecek);
            }
        //}
        //}
    }
    
//    public void Ulke_Dinlenme_Sayisi_Top_10_Goruntule() {
//        
//        modelUlkeDinlenmeSayisi.setRowCount(0);
//        
//        ArrayList<Sarki> sarkilar = new ArrayList<Sarki>();
//        
//        
//        sarkilar = kullaniciTop10Islemleri.UlkeDinlenmeSayisiTop10Getir();
//        
//        //if (sarkilar != null ) {
//        //for () {
//            for (/*Sarki sarki : sarkilar*/int i = 0; i < 10; i++) {
//                Object[] eklenecek = {sarkilar.get(i).getSarkiID(), sarkilar.get(i).getSarkiAd(), sarkilar.get(i).getSarkiTarih(), 
//                                      sarkilar.get(i).getSarkiSanatci(), sarkilar.get(i).getSarkiAlbum(), sarkilar.get(i).getSarkiTur(), 
//                                      sarkilar.get(i).getSarkiSure(), sarkilar.get(i).getDinlenmeSayisi()};
//                
//                modelUlkeDinlenmeSayisi.addRow(eklenecek);
//            }
//        //}
//        //}
//    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Top_10_Listeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Top_10_Listeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Top_10_Listeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Top_10_Listeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kullanici_Top_10_Listeleri dialog = new Kullanici_Top_10_Listeleri(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DinlenmeSayisiSarkiTablosu;
    private javax.swing.JButton DinlenmeSayisinaGoreEkle;
    private javax.swing.JButton DinlenmeSayisinaGoreSil;
    private javax.swing.JButton GeriButonu;
    private javax.swing.JTable JazzDinlenmeSayisiSarkiTablosu;
    private javax.swing.JButton JazzEkle;
    private javax.swing.JButton JazzSil;
    private javax.swing.JTable KlasikDinlenmeSayisiSarkiTablosu;
    private javax.swing.JButton KlasikEkle;
    private javax.swing.JButton KlasikSil;
    private javax.swing.JLabel KullaniciAdiAlani;
    private javax.swing.JTable PopDinlenmeSayisiSarkiTablosu;
    private javax.swing.JButton PopEkle;
    private javax.swing.JButton PopSil;
    private javax.swing.JComboBox<String> UlkeComboBox;
    private javax.swing.JTable UlkeDinlenmeSayisiSarkiTablosu;
    private javax.swing.JButton UlkeSecimButonu;
    private javax.swing.JButton UlkelereGoreEkle;
    private javax.swing.JButton UlkelereGoreSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
